from .common_imports import *
from .semantic_union import *
from .utils import *
from .custom_langchain_tools import *

if __name__ == "__main__":
    
    os.environ["OPENAI_API"]=getpass("Enter the OpenAI API Key: ")
    os.environ["OPENAI_ORG"]=getpass("Enter the OpenAI ORG Key: ")

    APP_ID = 'com.google.android.apps.nbu.paisa.user'
    APP_NAME = 'GooglePay'

    # Load the app from file datas/api_result_appdescr_{APP_NAME}.json
    # This file is generated by the google_play_scraper in Google Colab
    # Cannot be generated here due to CERTIFICATE_VERIFY_FAILED error
    with open('datas/api_result_appdescr_GooglePay.json', 'r') as f:
        loaded_api_result_app = json.load(f)
    loaded_api_result_app['title'] = APP_NAME

    # Generate the standardized app description
    # It takes the loaded_api_result_app dict generated by the google_play_scraper
    # It returns a dictionary with the standardized app description
    standard_app_description = generate_full_app_descritpion(
        api_result_app = loaded_api_result_app,
        general_descripion="App reviews of a Payment and UPI App",
        multi_qry_count_per_label=10
        )
    
    # Store the standardized app description
    with open(f"datas/standard_app_description_{standard_app_description['name']}_v{0}.json", 'w') as f:
        json.dump(standard_app_description, f)